// Generated by _src/optimize.mjs — static imports give next/image intrinsic sizes + blur placeholders.
import aerialDarkRoofs from "@/assets/photos/aerial-dark-roofs.jpg";
import aerialHouseGrey from "@/assets/photos/aerial-house-grey.jpg";
import aerialHousesTrees from "@/assets/photos/aerial-houses-trees.jpg";
import aerialSuburb from "@/assets/photos/aerial-suburb.jpg";
import aerialSuburbCurve from "@/assets/photos/aerial-suburb-curve.jpg";
import aerialTexas from "@/assets/photos/aerial-texas.jpg";
import beforeMossShingles from "@/assets/photos/before-moss-shingles.jpg";
import beforeOldHouse from "@/assets/photos/before-old-house.jpg";
import beforeOldShingles from "@/assets/photos/before-old-shingles.jpg";
import beforeRoofHole from "@/assets/photos/before-roof-hole.jpg";
import beforeShingleEdge from "@/assets/photos/before-shingle-edge.jpg";
import beforeWornRoof from "@/assets/photos/before-worn-roof.jpg";
import bluebonnetsHouse from "@/assets/photos/bluebonnets-house.jpg";
import commercialFlat from "@/assets/photos/commercial-flat.jpg";
import commercialRooftop from "@/assets/photos/commercial-rooftop.jpg";
import crewDrill from "@/assets/photos/crew-drill.jpg";
import crewGloves from "@/assets/photos/crew-gloves.jpg";
import crewHouse from "@/assets/photos/crew-house.jpg";
import crewMetalRoll from "@/assets/photos/crew-metal-roll.jpg";
import crewNailer from "@/assets/photos/crew-nailer.jpg";
import crewRidge from "@/assets/photos/crew-ridge.jpg";
import crewShingles1 from "@/assets/photos/crew-shingles-1.jpg";
import crewShingles2 from "@/assets/photos/crew-shingles-2.jpg";
import crewSteepRoof from "@/assets/photos/crew-steep-roof.jpg";
import downspout from "@/assets/photos/downspout.jpg";
import framingTrusses from "@/assets/photos/framing-trusses.jpg";
import fwCourthouse from "@/assets/photos/fw-courthouse.jpg";
import fwSkylineDusk from "@/assets/photos/fw-skyline-dusk.jpg";
import fwSkylineTrees from "@/assets/photos/fw-skyline-trees.jpg";
import fwSunset from "@/assets/photos/fw-sunset.jpg";
import fwTrinity from "@/assets/photos/fw-trinity.jpg";
import gableGolden from "@/assets/photos/gable-golden.jpg";
import gutterDrip from "@/assets/photos/gutter-drip.jpg";
import gutterRain from "@/assets/photos/gutter-rain.jpg";
import hailGrass from "@/assets/photos/hail-grass.jpg";
import hailGround from "@/assets/photos/hail-ground.jpg";
import hailHand from "@/assets/photos/hail-hand.jpg";
import homeowners from "@/assets/photos/homeowners.jpg";
import houseBlack from "@/assets/photos/house-black.jpg";
import houseBlackDusk from "@/assets/photos/house-black-dusk.jpg";
import houseBrickDusk from "@/assets/photos/house-brick-dusk.jpg";
import houseBrickRanch from "@/assets/photos/house-brick-ranch.jpg";
import houseBrickSuburb from "@/assets/photos/house-brick-suburb.jpg";
import houseDuskGlow from "@/assets/photos/house-dusk-glow.jpg";
import houseLitWindows from "@/assets/photos/house-lit-windows.jpg";
import houseLongDrive from "@/assets/photos/house-long-drive.jpg";
import houseMetalWhite from "@/assets/photos/house-metal-white.jpg";
import houseModernFarmhouse from "@/assets/photos/house-modern-farmhouse.jpg";
import housePinkSky from "@/assets/photos/house-pink-sky.jpg";
import houseRanchDusk from "@/assets/photos/house-ranch-dusk.jpg";
import houseStoneGable from "@/assets/photos/house-stone-gable.jpg";
import houseStoneRanch from "@/assets/photos/house-stone-ranch.jpg";
import houseTimberPorch from "@/assets/photos/house-timber-porch.jpg";
import houseWhiteClassic from "@/assets/photos/house-white-classic.jpg";
import ladderSky from "@/assets/photos/ladder-sky.jpg";
import metalAbstract from "@/assets/photos/metal-abstract.jpg";
import metalBlackGable from "@/assets/photos/metal-black-gable.jpg";
import metalCupola from "@/assets/photos/metal-cupola.jpg";
import metalDormers from "@/assets/photos/metal-dormers.jpg";
import metalEdge from "@/assets/photos/metal-edge.jpg";
import metalGable from "@/assets/photos/metal-gable.jpg";
import metalPeak from "@/assets/photos/metal-peak.jpg";
import metalSeams from "@/assets/photos/metal-seams.jpg";
import metalTwinPeaks from "@/assets/photos/metal-twin-peaks.jpg";
import posterHeroDrone from "@/assets/photos/poster-hero-drone.jpg";
import posterStormFront from "@/assets/photos/poster-storm-front.jpg";
import posterTearOff from "@/assets/photos/poster-tear-off.jpg";
import ranchMetalRoof from "@/assets/photos/ranch-metal-roof.jpg";
import rooferBack from "@/assets/photos/roofer-back.jpg";
import rooferClouds from "@/assets/photos/roofer-clouds.jpg";
import rooferHardhat from "@/assets/photos/roofer-hardhat.jpg";
import rooferPortrait from "@/assets/photos/roofer-portrait.jpg";
import shingleArchitectural from "@/assets/photos/shingle-architectural.jpg";
import shingleDark from "@/assets/photos/shingle-dark.jpg";
import shingleGrey from "@/assets/photos/shingle-grey.jpg";
import shingleRows from "@/assets/photos/shingle-rows.jpg";
import shingleSky from "@/assets/photos/shingle-sky.jpg";
import slateDark from "@/assets/photos/slate-dark.jpg";
import slateFishscale from "@/assets/photos/slate-fishscale.jpg";
import slateGrey from "@/assets/photos/slate-grey.jpg";
import stormAmber from "@/assets/photos/storm-amber.jpg";
import stormFarmhouse from "@/assets/photos/storm-farmhouse.jpg";
import stormHouse from "@/assets/photos/storm-house.jpg";
import stormPink from "@/assets/photos/storm-pink.jpg";
import stormRoad from "@/assets/photos/storm-road.jpg";
import stormShelf from "@/assets/photos/storm-shelf.jpg";
import stormSupercellRoad from "@/assets/photos/storm-supercell-road.jpg";
import stormWheat from "@/assets/photos/storm-wheat.jpg";
import teamForeman from "@/assets/photos/team-foreman.jpg";
import teamFounder from "@/assets/photos/team-founder.jpg";
import texasFlag from "@/assets/photos/texas-flag.jpg";
import texasSky from "@/assets/photos/texas-sky.jpg";
import tileBarrel from "@/assets/photos/tile-barrel.jpg";
import tileDark from "@/assets/photos/tile-dark.jpg";
import tileDormers from "@/assets/photos/tile-dormers.jpg";
import tileTerracotta from "@/assets/photos/tile-terracotta.jpg";
import trussesGolden from "@/assets/photos/trusses-golden.jpg";
import txRanchMetal from "@/assets/photos/tx-ranch-metal.jpg";
import txRanchPorch from "@/assets/photos/tx-ranch-porch.jpg";

export const photos = {
  "aerial-dark-roofs": aerialDarkRoofs,
  "aerial-house-grey": aerialHouseGrey,
  "aerial-houses-trees": aerialHousesTrees,
  "aerial-suburb": aerialSuburb,
  "aerial-suburb-curve": aerialSuburbCurve,
  "aerial-texas": aerialTexas,
  "before-moss-shingles": beforeMossShingles,
  "before-old-house": beforeOldHouse,
  "before-old-shingles": beforeOldShingles,
  "before-roof-hole": beforeRoofHole,
  "before-shingle-edge": beforeShingleEdge,
  "before-worn-roof": beforeWornRoof,
  "bluebonnets-house": bluebonnetsHouse,
  "commercial-flat": commercialFlat,
  "commercial-rooftop": commercialRooftop,
  "crew-drill": crewDrill,
  "crew-gloves": crewGloves,
  "crew-house": crewHouse,
  "crew-metal-roll": crewMetalRoll,
  "crew-nailer": crewNailer,
  "crew-ridge": crewRidge,
  "crew-shingles-1": crewShingles1,
  "crew-shingles-2": crewShingles2,
  "crew-steep-roof": crewSteepRoof,
  "downspout": downspout,
  "framing-trusses": framingTrusses,
  "fw-courthouse": fwCourthouse,
  "fw-skyline-dusk": fwSkylineDusk,
  "fw-skyline-trees": fwSkylineTrees,
  "fw-sunset": fwSunset,
  "fw-trinity": fwTrinity,
  "gable-golden": gableGolden,
  "gutter-drip": gutterDrip,
  "gutter-rain": gutterRain,
  "hail-grass": hailGrass,
  "hail-ground": hailGround,
  "hail-hand": hailHand,
  "homeowners": homeowners,
  "house-black": houseBlack,
  "house-black-dusk": houseBlackDusk,
  "house-brick-dusk": houseBrickDusk,
  "house-brick-ranch": houseBrickRanch,
  "house-brick-suburb": houseBrickSuburb,
  "house-dusk-glow": houseDuskGlow,
  "house-lit-windows": houseLitWindows,
  "house-long-drive": houseLongDrive,
  "house-metal-white": houseMetalWhite,
  "house-modern-farmhouse": houseModernFarmhouse,
  "house-pink-sky": housePinkSky,
  "house-ranch-dusk": houseRanchDusk,
  "house-stone-gable": houseStoneGable,
  "house-stone-ranch": houseStoneRanch,
  "house-timber-porch": houseTimberPorch,
  "house-white-classic": houseWhiteClassic,
  "ladder-sky": ladderSky,
  "metal-abstract": metalAbstract,
  "metal-black-gable": metalBlackGable,
  "metal-cupola": metalCupola,
  "metal-dormers": metalDormers,
  "metal-edge": metalEdge,
  "metal-gable": metalGable,
  "metal-peak": metalPeak,
  "metal-seams": metalSeams,
  "metal-twin-peaks": metalTwinPeaks,
  "poster-hero-drone": posterHeroDrone,
  "poster-storm-front": posterStormFront,
  "poster-tear-off": posterTearOff,
  "ranch-metal-roof": ranchMetalRoof,
  "roofer-back": rooferBack,
  "roofer-clouds": rooferClouds,
  "roofer-hardhat": rooferHardhat,
  "roofer-portrait": rooferPortrait,
  "shingle-architectural": shingleArchitectural,
  "shingle-dark": shingleDark,
  "shingle-grey": shingleGrey,
  "shingle-rows": shingleRows,
  "shingle-sky": shingleSky,
  "slate-dark": slateDark,
  "slate-fishscale": slateFishscale,
  "slate-grey": slateGrey,
  "storm-amber": stormAmber,
  "storm-farmhouse": stormFarmhouse,
  "storm-house": stormHouse,
  "storm-pink": stormPink,
  "storm-road": stormRoad,
  "storm-shelf": stormShelf,
  "storm-supercell-road": stormSupercellRoad,
  "storm-wheat": stormWheat,
  "team-foreman": teamForeman,
  "team-founder": teamFounder,
  "texas-flag": texasFlag,
  "texas-sky": texasSky,
  "tile-barrel": tileBarrel,
  "tile-dark": tileDark,
  "tile-dormers": tileDormers,
  "tile-terracotta": tileTerracotta,
  "trusses-golden": trussesGolden,
  "tx-ranch-metal": txRanchMetal,
  "tx-ranch-porch": txRanchPorch,
} as const;

export type PhotoKey = keyof typeof photos;
