// Optimizes _src/raw/*.jpg → src/assets/photos/*.jpg and writes the typed registry + SOURCES.md.
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
const sharp = createRequire(import.meta.url)("../node_modules/sharp");

const root = new URL("../", import.meta.url);
const outDir = new URL("src/assets/photos/", root);
mkdirSync(outDir, { recursive: true });

const manifest = Object.fromEntries(
  readFileSync(new URL("_src/manifest.txt", root), "utf8")
    .trim()
    .split(/\r?\n/)
    .map((l) => l.split("|"))
    .map(([name, id, , user, uname]) => [name, { id, user, uname }]),
);

const files = readdirSync(new URL("_src/raw/", root)).filter((f) => f.endsWith(".jpg"));
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const entries = [];

for (const f of files) {
  const name = f.replace(/\.jpg$/, "");
  const out = new URL(name + ".jpg", outDir);
  if (!existsSync(out)) {
    await sharp(new URL("_src/raw/" + f, root).pathname.slice(1).replace(/%20/g, " "))
      .rotate()
      .resize(2000, 2000, { fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: 78, mozjpeg: true, progressive: true })
      .toFile(out.pathname.slice(1).replace(/%20/g, " "));
  }
  entries.push(name);
}

entries.sort();
const lines = [
  "// Generated by _src/optimize.mjs — static imports give next/image intrinsic sizes + blur placeholders.",
  ...entries.map((n) => `import ${camel(n)} from "@/assets/photos/${n}.jpg";`),
  "",
  "export const photos = {",
  ...entries.map((n) => `  "${n}": ${camel(n)},`),
  "} as const;",
  "",
  "export type PhotoKey = keyof typeof photos;",
  "",
];
writeFileSync(new URL("src/lib/photos.ts", root), lines.join("\n"));

const src = [
  "# Image & video sources",
  "",
  "All photos are from [Unsplash](https://unsplash.com/license) (free to use) and videos from [Pexels](https://www.pexels.com/license/) (free to use).",
  "Optimized copies live in `src/assets/photos/` (served through next/image) and `public/video/`.",
  "",
  "| File | Source | Photographer |",
  "|---|---|---|",
  ...entries
    .filter((n) => manifest[n])
    .map((n) => `| ${n}.jpg | https://unsplash.com/photos/${manifest[n].id} | ${manifest[n].user} (@${manifest[n].uname}) |`),
  "",
  "## Video",
  "",
  "| File | Source | Author |",
  "|---|---|---|",
  "| video/hero-drone.mp4 (+ poster-hero-drone.jpg) | https://www.pexels.com/video/4770380/ | David McBee |",
  "| video/storm-front.mp4 (+ poster-storm-front.jpg) | https://www.pexels.com/video/29545625/ | Ndumiso Mvelase |",
  "| video/tear-off.mp4 (+ poster-tear-off.jpg) | https://www.pexels.com/video/4198810/ | K (Pexels) |",
  "",
];
mkdirSync(new URL("public/images/", root), { recursive: true });
writeFileSync(new URL("public/images/SOURCES.md", root), src.join("\n"));
console.log("optimized", entries.length);
